import {
  useEffect,
  useId,
  useRef,
  useState,
  useTransition,
  type FormEvent,
} from "react";
import { IconArrowRight, IconCheck, IconCopy } from "./icons";

// 与后端 schema CHECK 约束保持一致
const SLUG_RE = /^[a-z0-9][a-z0-9-]{1,48}[a-z0-9]$|^[a-z0-9]{3}$/;
const RESERVED = new Set([
  "api",
  "auth",
  "create",
  "dashboard",
  "edit",
  "warn",
  "assets",
  "static",
]);

const SLUG_ALPHABET = "23456789abcdefghjkmnpqrstuvwxyz";

function genSlug(): string {
  let s = "";
  for (let i = 0; i < 6; i++) {
    s += SLUG_ALPHABET[Math.floor(Math.random() * SLUG_ALPHABET.length)];
  }
  return s;
}

function isValidUrl(raw: string): boolean {
  try {
    const u = new URL(raw);
    return u.protocol === "http:" || u.protocol === "https:";
  } catch {
    return false;
  }
}

// 占位 host. SSR 时 window 不可用; 客户端 hydrate 后 useEffect 把它换成真实 host,
// 避免 hydration mismatch.
const PLACEHOLDER_HOST = "o.dev";

type Result = { slug: string; url: string };

type CreateFormProps = {
  /** /edit/[slug] 进入时, 用 URL slug 预填表单. */
  initialSlug?: string;
};

export function CreateForm({ initialSlug }: CreateFormProps) {
  const urlId = useId();
  const slugId = useId();
  const pubId = useId();

  const [url, setUrl] = useState("");
  const [slug, setSlug] = useState(initialSlug ?? "");
  const [isPublic, setIsPublic] = useState(true);
  const [errors, setErrors] = useState<{ url?: string; slug?: string; form?: string }>({});
  const [result, setResult] = useState<Result | null>(null);
  const [copied, setCopied] = useState(false);
  const [pending, startTransition] = useTransition();
  // SSR 阶段没有 window, 用占位 host 渲染; 客户端挂载后再换成真实 host.
  const [host, setHost] = useState<string>(PLACEHOLDER_HOST);
  const copyTimer = useRef<number | null>(null);
  const urlInputRef = useRef<HTMLInputElement | null>(null);

  useEffect(() => {
    if (typeof window !== "undefined") {
      setHost(window.location.host);
    }
  }, []);

  // /edit/[slug] 进入时, slug 已预填, 自动把焦点放到 URL 输入框, 让用户直接打目标链接.
  useEffect(() => {
    if (initialSlug && urlInputRef.current) {
      urlInputRef.current.focus();
    }
  }, [initialSlug]);

  function validate(slugFinal: string): { url?: string; slug?: string } | null {
    const next: { url?: string; slug?: string } = {};
    if (!url.trim()) next.url = "请输入要缩短的链接";
    else if (!isValidUrl(url.trim())) next.url = "需要 http:// 或 https:// 开头的有效链接";

    if (slugFinal) {
      if (RESERVED.has(slugFinal)) next.slug = "该 slug 是保留路径";
      else if (!SLUG_RE.test(slugFinal))
        next.slug = "只允许 a-z0-9-, 首尾字母数字, 长度 3-50";
    }
    return Object.keys(next).length ? next : null;
  }

  async function postCreate(slugFinal: string, urlFinal: string): Promise<
    | { ok: true; slug: string }
    | { ok: false; kind: "taken" | "invalid" | "network"; message?: string }
  > {
    try {
      const res = await fetch("/api/v1/links", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ slug: slugFinal, url: urlFinal }),
      });
      if (res.status === 201) return { ok: true, slug: slugFinal };
      if (res.status === 409) return { ok: false, kind: "taken" };
      if (res.status === 400) {
        const body = (await res.json().catch(() => null)) as
          | { error?: string }
          | null;
        return { ok: false, kind: "invalid", message: body?.error };
      }
      return { ok: false, kind: "network", message: `HTTP ${res.status}` };
    } catch (err) {
      return {
        ok: false,
        kind: "network",
        message: err instanceof Error ? err.message : "网络异常",
      };
    }
  }

  function onSubmit(e: FormEvent) {
    e.preventDefault();
    const cleaned = slug.trim().toLowerCase();
    const slugFinal = cleaned || genSlug();
    const errs = validate(slugFinal);
    if (errs) {
      setErrors(errs);
      return;
    }
    setErrors({});

    startTransition(() => {
      void (async () => {
        // 自动生成的 slug 撞库时, 重试一次
        const autoGenerated = !cleaned;
        let attempt = await postCreate(slugFinal, url.trim());
        if (!attempt.ok && attempt.kind === "taken" && autoGenerated) {
          attempt = await postCreate(genSlug(), url.trim());
        }

        if (attempt.ok) {
          startTransition(() => {
            setResult({ slug: attempt.slug, url: url.trim() });
          });
          return;
        }

        const msg =
          attempt.kind === "taken"
            ? "该 slug 已被占用, 换一个试试"
            : attempt.kind === "invalid"
              ? "输入不合法, 检查 URL/slug 格式"
              : `创建失败: ${attempt.message ?? "未知错误"}`;
        startTransition(() => {
          setErrors(
            attempt.kind === "taken" ? { slug: msg } : { form: msg },
          );
        });
      })();
    });
  }

  async function copyToClipboard(text: string) {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      if (copyTimer.current) window.clearTimeout(copyTimer.current);
      copyTimer.current = window.setTimeout(() => setCopied(false), 1600);
    } catch {
      setCopied(false);
    }
  }

  function reset() {
    setResult(null);
    setUrl("");
    setSlug(initialSlug ?? "");
    setIsPublic(true);
    setErrors({});
    setCopied(false);
  }

  if (result) {
    const protocol =
      typeof window !== "undefined" ? window.location.protocol : "https:";
    const shortUrl = `${protocol}//${host}/${result.slug}`;
    return (
      <div className="create-form" role="status" aria-live="polite">
        <div className="create-success">
          <div className="create-success__title">短链已生成</div>
          <div className="create-success__url">
            <span className="create-success__url__text">{shortUrl}</span>
            <button
              type="button"
              className="btn btn--ghost btn--sm"
              onClick={() => copyToClipboard(shortUrl)}
              aria-label="复制短链"
            >
              {copied ? <IconCheck /> : <IconCopy />}
              <span>{copied ? "已复制" : "复制"}</span>
            </button>
          </div>
          <p className="create-success__hint">
            指向 <span style={{ color: "var(--text)" }}>{result.url}</span>
          </p>
          <div className="create-success__row">
            <a
              className="btn btn--primary btn--sm"
              href={`/${result.slug}`}
              target="_blank"
              rel="noreferrer"
            >
              打开
            </a>
            <button
              type="button"
              className="btn btn--ghost btn--sm"
              onClick={reset}
            >
              再创建一个
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <form className="create-form" onSubmit={onSubmit} noValidate>
      <div className="field">
        <label className="field__label" htmlFor={urlId}>
          目标链接
        </label>
        <input
          id={urlId}
          ref={urlInputRef}
          type="url"
          inputMode="url"
          autoComplete="off"
          spellCheck={false}
          value={url}
          onChange={(e) => setUrl(e.target.value)}
          placeholder="https://example.com/very/long/path"
          className="field__input"
          aria-invalid={!!errors.url}
          aria-describedby={errors.url ? `${urlId}-err` : undefined}
          required
        />
        <div id={`${urlId}-err`} className="field__error">
          {errors.url ?? " "}
        </div>
      </div>

      <div className="field">
        <label className="field__label" htmlFor={slugId}>
          自定义 slug <span style={{ color: "var(--text-faint)" }}>(可选)</span>
        </label>
        <div className="field__prefix-wrap">
          <span className="field__prefix">{host}/</span>
          <input
            id={slugId}
            type="text"
            autoComplete="off"
            spellCheck={false}
            value={slug}
            onChange={(e) => setSlug(e.target.value)}
            placeholder="留空自动生成"
            className="field__input field__input--with-prefix"
            aria-invalid={!!errors.slug}
            aria-describedby={errors.slug ? `${slugId}-err` : undefined}
            maxLength={50}
          />
        </div>
        <div id={`${slugId}-err`} className="field__error">
          {errors.slug ?? " "}
        </div>
      </div>

      <div className="create-form__actions">
        <label className="checkbox" htmlFor={pubId}>
          <input
            id={pubId}
            type="checkbox"
            checked={isPublic}
            onChange={(e) => setIsPublic(e.target.checked)}
          />
          <span>公开可见</span>
        </label>
        <button
          type="submit"
          className="btn btn--primary"
          disabled={pending}
          aria-busy={pending}
        >
          <span>{pending ? "创建中" : "创建短链"}</span>
          <IconArrowRight />
        </button>
      </div>
      {errors.form ? (
        <div className="field__error" role="alert" style={{ marginTop: 8 }}>
          {errors.form}
        </div>
      ) : null}
    </form>
  );
}
